# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdevice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevice',
            options={'verbose_name': 'Device in use', 'verbose_name_plural': 'Devices in use'},
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='status',
            field=models.CharField(choices=[('sleep', 'sleep'), ('working', 'working'), ('off', 'off'), ('not-used', 'not used')], max_length=10),
        ),
    ]
