# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdevice', '0002_auto_20170904_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
