# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdevice', '0003_auto_20170904_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
