# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdevice', '0004_userdevice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='userdevice.UserDevice')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
