# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 18:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('sleep', 'sleep'), ('working', 'working'), ('off', 'off')], max_length=10)),
                ('attribute', django.contrib.postgres.fields.jsonb.JSONField()),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Device',
                'verbose_name': 'User Device',
            },
        ),
    ]
