# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdevice', '0006_auto_20171109_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
