# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 09:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdevice', '0007_auto_20171109_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('user_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='userdevice.UserDevice')),
            ],
            options={
                'verbose_name_plural': 'History',
                'verbose_name': 'History',
            },
        ),
    ]
