# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdevice', '0008_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='attributes',
            new_name='attribute',
        ),
    ]
